# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.srcs/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1.xci
# IP: The module: 'axi_gpio_caa_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.gen/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_caa_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.gen/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_caa_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.gen/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_caa_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.srcs/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1.xci
# IP: The module: 'axi_gpio_caa_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.gen/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_caa_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.gen/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_caa_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Char/Documents/ECE_520/Fall_26/axi_gpio_caa/axi_gpio_caa.gen/sources_1/bd/axi_gpio_caa/ip/axi_gpio_caa_axi_gpio_0_1/axi_gpio_caa_axi_gpio_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_gpio_caa_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
